dinesafelysite/views.py
restaurant/tests.py

restaurant recommendation feature. gathering preference list of the user and recommending restauratns based on that

Recommendation view

---

restaurant/templates/restaurant_detail.html

Fix bug - Restaurant Opening Hours showing undefined values
In restaurant detail page, some of the restaurant opening hours show undefined values. The original design didn't consider the situation where there are multiple opening hours on the same day.

Fix bug - Restaurant Opening Hours showing undefined values

---

templates/contact_us.html
templates/request_received.html

Added contact_us.html and request_received.html for contact form feature.

Contact form frontend

---

restaurant/templates/faqs.html
restaurant/urls.py
templates/base.html
user/templates/contact_us.html

Changes: 
- Added FAQ page
- Modified base.html to add the FAQ tab and reformat tab spacing 
- Centered the contact form (with center tags)

Added FAQ Page, modified base.html tabs, centered contact form

---

restaurant/tests.py

Added tests for sort by rating/price/distance

Wrote tests for sort by rating/price/distance feature

---

restaurant/templates/faqs.html
templates/base.html

The FAQ question boxes had an outline issue due to specifications with the on event listener. This bug was resolved by explicitly declaring no outline in the class="collapsible".

Faq outline bug fix

---

chatbot/templates/chat.html

Fix the chatbot time issue by adding "0" in front of minutes if the minute is less than 10.
Previous behavior: If the time is 14:02, it'll display 14:2.
Current behavior: If the time is 14:02, it'll display 14:02.

Fix chatbot time issue

---

restaurant/tests.py
user/tests.py

1. Wrote tests for restaurant Q&As forms
2. Wrote tests for restaurant Q&As views

Wrote tests for restaurant Q&As feature

---

restaurant/templates/restaurant_detail.html
restaurant/views.py

-implemented the front end
-changed the restaurant limit in the views

restaurant recommendation front end

---

dinesafelysite/views.py
templates/index.html

-altered the frontend to show recommended restaurants (based on recent views) on the main page
-altered the views.py to pass an empty list to the front end (this needs to be edited later)

Recommend restaurants based on recent views frontend

---

restaurant/templates/answer_community.html
restaurant/templates/ask_community.html
restaurant/templates/restaurant_detail.html
restaurant/tests.py
restaurant/urls.py
restaurant/views.py

- Modify frontend and backend to add pagination for restaurant Q&As
- Modify tests, change template name, change path/urls name

Added pagination for restaurant Q&As

---

update_compliant_status.py

- Get latest inspection records to update COVID compliant status
- Compliant filter issue was fixed

Update COVID compliant status to fix compliant filter

---

user/tests.py

In this PR, I added more tests

User viewing history frontend

---

user/templates/view_history.html
user/views.py

- Add last visited date for view history page

Add view history date

---

user/templates/profile.html

- Update the user default avatar so that it won't show the broken image

fix default avatar bug

---

restaurant/tests.py
user/templates/profile.html
user/tests.py
user/views.py

- Fix remove user avatar bug
- Add reset user avatar to default one feature
- Wrote tests

Fix remove avatar

---

delete_old_inspection_records.py

currently frees up around 2750 rows

script to delete oldest inspection records for each restaurant

---

restaurant/templates/faqs.html

The purpose of this PR is to reformat the DineLine Logo in the navigation bar on the FAQ page. The original behavior had unnecessary margin around the container defined in the faq.html file, which was removed, resolving the issue. The intended behavior is having the DineLine logo in the same position on the navigation bar across webpages on DineLine. 
- [x ] My code follows the code style of this project

faq-logo-reposition

---

check_database.py

Check & Reduce Database Records
This script checks the database rows. If the records exceed 10000 lines, it will be reduced by deleting user activity records 10 days ago. If it still exceeds, it will delete accessibility records that don't match any restaurant.

Check & Reduce Database Records

---

templates/index.html
user/templates/register.html
user/templates/reset_password_template.html

change instances of dine safe.ly to DineLine

changes remaining instances of dine safe.ly to DineLine

---

templates/index.html
user/templates/register.html
user/templates/reset_password_template.html
user/utils.py

replace "dinesafely" with "DineLine" across all webpages
replaced "dinesafely" with "DineLine" across all webpages so that user sees "DineLine" when they use the app

replace "dinesafely" with "DineLine"

---

.circleci/config.yml

Have to add COVERALLS_REPO_TOKEN environment variable to circleci

Add coveralls to circleci

---

.github/pull_request_template.md
Procfile
check_database.py
dinesafelysite/views.py
restaurant/utils.py

Add scheduler & Update latest compliant restaurants & Update doc
1. Add scheduler to the check database script
2. Add MOPD compliant restaurants to the latest compliant restaurants list in the home page
3. Add "Enhancement" type of changes to the pull request template

Add scheduler & Update latest compliant restaurants & Update doc

---

restaurant/templates/browse.html

Possible fix for the browse page restaurants cards bug
The purpose of this PR is to fix the browse page restaurant cards bug. We intend to load 6 cards initially, but the current production instance displays 2 cards when the user loads the browse page. This PR attempts to make the loading synchronous and possibly fix the issue.

Browse restaurant cards bug
